import Maison from './Maison';
import Head from 'next/head'
import Layout from '@/components/Layout/Layout'

export default function rental() {
  
  return (
    <>
      <Head>
        <title>Cryptokey DApp : Get the number</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <Maison
          imageSrc="https://media.istockphoto.com/id/168376723/fr/photo/nouvelle-maison-avec-la-vue-sur-le-jardin-einfamilienhaus-trajet.jpg?s=2048x2048&w=is&k=20&c=T8qgyZXdDv--tidG-ukBfVlvdelWI2ge1C1qR63H2EI="
          title="Maison 1"
          description="Une belle maison dans un quartier tranquille"
        />
        <Maison
          imageSrc="https://media.istockphoto.com/id/168376723/fr/photo/nouvelle-maison-avec-la-vue-sur-le-jardin-einfamilienhaus-trajet.jpg?s=2048x2048&w=is&k=20&c=T8qgyZXdDv--tidG-ukBfVlvdelWI2ge1C1qR63H2EI="
          title="Maison 2"
          description="Une grande maison avec un beau jardin"
        />
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <Maison
          imageSrc="https://media.istockphoto.com/id/168376723/fr/photo/nouvelle-maison-avec-la-vue-sur-le-jardin-einfamilienhaus-trajet.jpg?s=2048x2048&w=is&k=20&c=T8qgyZXdDv--tidG-ukBfVlvdelWI2ge1C1qR63H2EI="
          title="Maison 3"
          description="Une maison moderne avec une belle vue sur la mer"
        />
        <Maison
          imageSrc="https://media.istockphoto.com/id/168376723/fr/photo/nouvelle-maison-avec-la-vue-sur-le-jardin-einfamilienhaus-trajet.jpg?s=2048x2048&w=is&k=20&c=T8qgyZXdDv--tidG-ukBfVlvdelWI2ge1C1qR63H2EI="
          title="Maison 4"
          description="Une petite maison confortable avec une cheminée"
        />
      </div>
    </div>
    </Layout>
    </>
  );
};