import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import { useAccount } from 'wagmi'
import { AspectRatio  } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
} from '@chakra-ui/react'
import Upload from '@/components/Upload'
import Mint from '@/components/Mint'

export default function Home() {

  const { isConnected } = useAccount()
  
  return (
    <>
      <Head>
        <title>Cryptokey DApp : Home</title>
        <meta name="description" content="Generated by cryptokey app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
            <iframe width="800" height="500"
            src="https://www.youtube.com/embed/omwPuLRim0U?autoplay=1&mute=1&loop=1&controls=0">
            </iframe>
        ) : (
          <Alert borderRadius="10" fontFamily="fantasy" textAlign="center" status='info' width="50%" height="10%">
          <AlertIcon />
          Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}