import Rental from '../components/Rental';
import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import { address, useAccount, useProvider, useContractEvent } from 'wagmi'
import { Text, useToast, Flex, Button } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon
} from '@chakra-ui/react'
import { useEffect, useState } from 'react'
import { ethers } from 'ethers'
import { contractFactoryAddress, abiFactory } from "../public/constants/factory.js"
import { contractAddress, abi } from "../public/constants/contract.js"

export default function rental() {
 
  const {address, isConnected } = useAccount()
  const provider = useProvider()
  const toast = useToast()

  const [number, setNumber] = useState(null);
  // const [rentals, setRentals] = useState([]);
  
  useEffect(() =>{
    getRental();
  },[]);

  const getRental = async() => {
  
  try {
    const contractFactory = new ethers.Contract(contractFactoryAddress, abiFactory, provider)
    const data = await contractFactory.getRentalCollections(address);
    // setRentals(data);
    const contract = new ethers.Contract(contractAddress, abi, provider)
    // const rental = await contract.getOwnerRentals();
    // alert(rental);
  }
  catch(e) {
    toast({
        title: 'Error',
        description: `${String(e)}`,
        status: 'error',
        duration: 5000,
        isClosable: true,
    })
    console.log(e)
  }

}
  
  return (
    <>
      <Head>
        <title>Cryptokey DApp : See the rentals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      {isConnected ? (
      <div>
        {/* <div style={{ display: 'flex', justifyContent: 'space-between' }}> */}
        <Flex alignItems="center">
            <Button colorScheme='blue' onClick={() => getRental()}>Get rentals</Button>
            {number ? (
                <Text ml="1rem">{number}</Text> 
            ) : (
                <Text ml="1rem">Please, click on this button to get the number.</Text>
            )}
        </Flex>
        {/* <Rental
          imageSrc="https://media.istockphoto.com/id/168376723/fr/photo/nouvelle-maison-avec-la-vue-sur-le-jardin-einfamilienhaus-trajet.jpg?s=2048x2048&w=is&k=20&c=T8qgyZXdDv--tidG-ukBfVlvdelWI2ge1C1qR63H2EI="
          title="Rental 1"
          description="Une belle maison dans un quartier tranquille"
        /> */}
        </div>
      // </div>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  );
};